.set	GAME_STATE_ADDR,	0x804f9cc0
.set	GAME_MODE_ADDR,		0x804fa798
.set	SHOT_PARAMETERS_ADDR,	0x80518974
.set	FREE_CAMERA_STATUS_ADDR, 0x801d1c20
.set	NERF_SIM_STATUS_ADDR,	0x801d1c28
.set	DROP_BALL_STATUS_ADDR,	0x801d1c2c
.set	FREE_CAMERA_DELTA_ADDR,	0x801d1c30 # x, z, y, scale
.set	FREE_CAMERA_ABS_COORDS_ADDR,	0x801d1c40 #x, z, y
.set	PLAYER_POSITION_DUMP_ADDR,		0x801d1c50
.set	PLAYER_POSITION_DUMP_STATUS_ADDR,	0x801d1c5c
.set	ACTIVE_PLAYER_CLUB_ID_SAVE_ADDR,	0x801d1c60
.set	PUTT_IMPACT_DELTA_SAVE_ADDR,		0x801d1c6c
.set	GET_ACTIVE_GREAT_PLAYER_STATE_FUN_ADDR,	0x804016bc
.set	UPDATE_SIM_LINE_ADDR,	0x80416264
.set	GET_CONTROL_STAT_ADDR,	0x8044efd0
.set	CONST_PI_OVER_9_ADDR,	0x804ec0a0
.set	CONST_1_OVER_4_ADDR,	0x804ec3b4
.set	CONST_ONE_THIRD_ADDR,	0x804ec458
.set	CONST_ONE_EIGHTH_ADDR,	0x804ec45c
.set	CONST_10_ADDR,			0x804ec478
.set	CONST_3_OVER_1600_ADDR,	0x804f4b00
.set	DROP_BALL_IMPACT_WAIT_ADDR,	0x8053738c
.set	GAMEPLAY_STATUS_FROM_GREAT_PLAYER_STATE,	0x24
.set	PLAYER_PARAMETERS_FROM_GREAT_PLAYER_STATE,	0x4448
.set	BUTTON_HOLD_FROM_PLAYER_PARAMETERS,			0x100
.set	BUTTON_PRESS_FROM_PLAYER_PARAMETERS,		0x104
.set	ANALOGUE_STICK_FROM_PLAYER_PARAMETERS,		0x120
.set	C_STICK_FROM_PLAYER_PARAMETERS,				0x128
.set	ACTION_STATE_FROM_PLAYER_PARAMETERS,		0x1c4
.set	SHOT_MODE_FROM_PLAYER_PARAMETERS,			0x1cc
.set	CLUB_ID_FROM_PLAYER_PARAMETERS,				0x1d4
.set	IMPACT_NUM_BUTTON_PRESSES_FROM_PLAYER_PARAMETERS,	0x24c
.set	MAX_CHARGE_NUM_FRAMES_FROM_PLAYER_PARAMETERS,	0x250
.set	TOTAL_FRAMES_FROM_SIM_PATH,					0xd4
.set	PRE_BOUNCE_FRAMES_FROM_SIM_PATH,			0x14c
.set	LAUNCH_VELO_FROM_SHOT_PARAMETERS,			0x48
.set	NATURAL_SPIN_FROM_SHOT_PARAMETERS,			0x50
.set	BALL_FLYING_STATE_BASE_FROM_GREAT_PLAYER_STATE,	0x8
.set	BALL_FLYING_STATE_FROM_BASE,	0xe8
.set	PLAYER_POSITION_FROM_BASE,		0xb4
.set	STROKE_COUNT_BYTE_FROM_BASE,	0x1bc
.set	BALL_POSITION_FROM_BALL_FLYING_STATE,	0x9c

.set	IMPACT_STRUCT_ADDR,	0x80537388
.set	IMPACT_DELTA_FROM_IMPACT_STRUCT,	0x8
.set	SWEETSPOT_SIZE_FROM_IMPACT_STRUCT,	0xc
.set	SHOT_CHARGE_NUM_FRAMES_FROM_IMAPCT_STRUCT,	0x14
.set	PLAYER_PARAMETERS_FROM_IMPACT_STRUCT,	0x34
.set	MAX_IMPACT_METER_DRAW_SIZE,	10

.set	THETA_FROM_SHOT_PARAMETERS,		0x40

.set	GAME_MODE_PRACTICE,		3
.set	GREAT_GAMEPLAY_STATUS_BALL_FLYING,	7
.set	SIM_LINE_MODE_TRAINING,	7
.set	ACTION_STATE_IDLE,		5
.set	ACTION_STATE_PANNING,	6
.set	ACTION_STATE_2D_VIEW,	8
.set	ACTION_STATE_CHARGING,	11
.set	ACTION_STATE_SWING,		12
.set	CLUB_ID_PUTTER,			13
.set	SIM_LINE_DEFAULT_VISIBLE_FRAMES,	0x707
.set	SIM_LINE_VISIBLE_FRAMES,	8
.set	PUTT_IMPACT_CAP_FRAMES,		16
.set	PUTT_IMPACT_CAP_FRAMES_NEG,	-PUTT_IMPACT_CAP_FRAMES

.set	NERF_SIM_INACTIVE,		0
.set	NERF_SIM_NO_STAR,		1
.set	NERF_SIM_NO_HEIGHT_MAP,	2
.set	FREE_CAMERA_INACTIVE,	0
.set	FREE_CAMERA_ACTIVE,		1
.set	DROP_BALL_INACTIVE,		0
.set	DROP_BALL_START,		1
.set	DROP_BALL_PROCEED,		-0x1000
.set	NO_ANALOGUE_STICK_MASK,	0xfff0 # all buttons - D-pad (or analuogue trigger)
.set	MODIFIER_MASK,			0x10 # Z
.set	FREE_CAMERA_ACTIVATE_PRESS_MASK,	0x400 # X
# .set	EXEC_BUTTON_MASK_FIRST,	0x10 # Z
# .set	IGNORE_BUTTON_MASK,		0x01f # Z + D-pad
.set	FREE_CAMERA_EXIT_BUTTON_MASK,		0xffe0 # complement of above
.set	PRACTICE_RESTORE_SIM_HOLD_MASK,	0x110 # Z+A
