.set	GAME_STATE_ADDR,	0x804f9cc0
.set	GAME_MODE_ADDR,		0x804fa798
.set	FREE_CAMERA_STATUS_ADDR, 0x801d1c20
.set	NERF_SIM_STATUS_ADDR,	0x801d1c28
.set	FREE_CAMERA_COORDS_ADDR,	0x801d1c30 # x, z, y
.set	GET_ACTIVE_GREAT_PLAYER_STATE_FUN_ADDR,	0x804016bc
.set	PLAYER_PARAMETERS_FROM_GREAT_PLAYER_STATE,	0x4448
.set	BUTTON_HOLD_FROM_PLAYER_PARAMETERS,			0x100
.set	BUTTON_PRESS_FROM_PLAYER_PARAMETERS,		0x104
.set	ACTION_STATE_FROM_PLAYER_PARAMETERS,		0x1c4
.set	CLUB_ID_FROM_PLAYER_PARAMETERS,				0x1d4
.set	TOTAL_FRAMES_FROM_SIM_PATH,					0xd4
.set	PRE_BOUNCE_FRAMES_FROM_SIM_PATH,			0x14c
.set	GAME_MODE_PRACTICE,		3
.set	ACTION_STATE_IDLE,		5
.set	ACTION_STATE_PANNING,	6
.set	ACTION_STATE_2D_VIEW,	8
.set	CLUB_ID_PUTTER,			13
.set	SIM_LINE_VISIBLE_FRAMES,	10

.set	NERF_SIM_INACTIVE,		0
.set	NERF_SIM_NO_STAR,		1
.set	NERF_SIM_NO_HEIGHT_MAP,	2
.set	FREE_CAMERA_INACTIVE,	0
.set	FREE_CAMERA_ACTIVE,		1
.set	MODIFIER_MASK,			0x10 # Z
.set	FREE_CAMERA_ACTIVATE_PRESS_MASK,	0x400 # X
# .set	EXEC_BUTTON_MASK_FIRST,	0x10 # Z
# .set	IGNORE_BUTTON_MASK,		0x01f # Z + D-pad
.set	FREE_CAMERA_EXIT_BUTTON_MASK,		0xffe0 # complement of above
